  on:
    workflow_dispatch:
    push:
      paths:
        - .github/workflows/release.yml
        - .github/.version
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Read .version file
          id: version
          run: echo "::set-output name=version::$(cat .github/.version)"

        - name: Set up JDK 21
          uses: actions/setup-java@v3
          with:
            java-version: '21'
            distribution: 'corretto'
            cache: maven

        - name: Build with Maven
          run: |
            sed -i 's/0.0.0/${{ steps.version.outputs.version }}/g' pom.xml
            grep pom.xml -e ${{ steps.version.outputs.version }}
            mvn -B package --file pom.xml
            mv target/gta-v-tools-*.jar target/gta-v-tools.jar
        - uses: actions/upload-artifact@v3
          with:
            name: artifacts
            path: target/*.jar
        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            prerelease: false
            repo_token: ${{ github.token }}
            title: v${{ steps.version.outputs.version }}
            automatic_release_tag: v${{ steps.version.outputs.version }}
            files: |
              target/gta-v-tools.jar